In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [5]:
## Importing Data set ords_prods_merge
df_ords_prods_merge = pd.read_pickle(r'/Users/javieraquezada/Desktop/05-2025 Instacart Basket Analysis/02 Data/Prepared Data/ords_prods_merge_new_variables2.pkl')

In [ ]:
##Creating Path
path = r'/Users/javieraquezada/Desktop/05-2025 Instacart Basket Analysis'

In [6]:
## Step2
df_ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1.0     15.457838
2.0     17.277920
3.0     17.170395
4.0     17.811403
5.0     15.215751
6.0     16.439806
7.0     17.225802
8.0     15.340650
9.0     15.895474
10.0    20.197148
11.0    16.170638
12.0    15.887671
13.0    16.583536
14.0    16.773669
15.0    16.165037
16.0    17.665606
17.0    15.694469
18.0    19.310397
19.0    17.177343
20.0    16.473447
21.0    22.902379
Name: order_number, dtype: float64

In [8]:
## Step.3 Numbers might differ from the mean of the department_id in the full dataframe and the subset. 
## the substet seams to be an underrrepresentation in comparison with the full dataframe.

In [9]:
## printing
df_ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15891507
Loyal customer      10294027
New customer         6249525
Name: count, dtype: int64

In [10]:
## performed already.

In [15]:
## Step.5 Basic Statistics
df_ords_prods_merge.groupby('loyalty_flag')['prices'].describe()

,count,mean,std,min,25%,50%,75%,max
loyalty_flag,,,,,,,,
Loyal customer,10284093.0,10.386336,328.017787,1.0,4.2,7.4,11.2,99999.0
New customer,6243990.0,13.294670,597.560299,1.0,4.2,7.4,11.3,99999.0
Regular customer,15876776.0,12.495717,539.720919,1.0,4.2,7.4,11.3,99999.0

In [13]:
## New Customers have a tendency in purchasing more expensive products than Loyal Customers

In [16]:
##Creating a new filtered data frame do get rid of extreme outliers.
df_ords_prods = df_ords_prods_merge[df_ords_prods_merge['prices'] <= 15]

In [17]:
##  Repeating Step.5 Basic Statistics
df_ords_prods.groupby('loyalty_flag')['prices'].describe()

                       count      mean       std  min  25%  50%   75%   max
loyalty_flag
Loyal customer    10164157.0  7.623643  3.982989  1.0  4.2  7.3  11.0  15.0
New customer       6158338.0  7.626217  4.010681  1.0  4.2  7.3  11.1  15.0
Regular customer  15664686.0  7.626762  4.001785  1.0  4.2  7.3  11.1  15.0

In [18]:
## We change insight: Loyal Customers have a tendency to spend more in purchasing than New Customers

In [21]:
##Step 6. Creating a new flag
#### Splitting the data into groups based on user_id.
## Applying the transform() function on the prices columnn to generate the mean orders for each user.
##Create a new column,"mean_prices" into which you'll place the results of your aggregation.

# Calculate the mean price per user
df_ords_prods['mean_prices'] = df_ords_prods.groupby('user_id')['prices'].transform('mean')

/var/folders/n5/lt6zjw5j12s3tv1t42m14nqh0000gn/T/ipykernel_14229/3955083232.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ords_prods['mean_prices'] = df_ords_prods.groupby('user_id')['prices'].transform('mean')

In [25]:
## for checking all 100 rows
pd.options.display.max_rows = None

In [26]:
df_ords_prods.head(100)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,prices,price_range_loc,busiest_day,busiest_days,busiests_days,busiest_period_of_day,max_order,loyalty_flag,mean_price_order,mean_prices
0,0,2539329,1,1,2,8,NaN,196,1,0,...,9.0,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
1,0,2539329,1,1,2,8,NaN,14084,2,0,...,12.5,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
2,0,2539329,1,1,2,8,NaN,12427,3,0,...,4.4,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
3,0,2539329,1,1,2,8,NaN,26088,4,0,...,4.7,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
4,0,2539329,1,1,2,8,NaN,26405,5,0,...,1.0,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
5,1,2398795,1,2,3,7,15.0,196,1,1,...,9.0,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
6,1,2398795,1,2,3,7,15.0,10258,2,0,...,3.0,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
7,1,2398795,1,2,3,7,15.0,12427,3,1,...,4.4,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
8,1,2398795,1,2,3,7,15.0,13176,4,0,...,10.3,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
9,1,2398795,1,2,3,7,15.0,26088,5,1,...,4.7,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
10,1,2398795,1,2,3,7,15.0,13032,6,0,...,4.0,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
11,2,473747,1,3,3,12,21.0,196,1,1,...,9.0,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
12,2,473747,1,3,3,12,21.0,12427,2,1,...,4.4,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
13,2,473747,1,3,3,12,21.0,10258,3,1,...,3.0,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
14,2,473747,1,3,3,12,21.0,25133,4,0,...,8.6,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
15,2,473747,1,3,3,12,21.0,30450,5,0,...,3.2,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
16,3,2254736,1,4,4,7,29.0,196,1,1,...,9.0,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
17,3,2254736,1,4,4,7,29.0,12427,2,1,...,4.4,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
18,3,2254736,1,4,4,7,29.0,10258,3,1,...,3.0,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
19,3,2254736,1,4,4,7,29.0,25133,4,1,...,8.6,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
20,3,2254736,1,4,4,7,29.0,26405,5,1,...,1.0,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
21,4,431534,1,5,4,15,28.0,196,1,1,...,9.0,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
22,4,431534,1,5,4,15,28.0,12427,2,1,...,4.4,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
23,4,431534,1,5,4,15,28.0,10258,3,1,...,3.0,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
24,4,431534,1,5,4,15,28.0,25133,4,1,...,8.6,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
25,4,431534,1,5,4,15,28.0,10326,5,0,...,2.7,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
26,4,431534,1,5,4,15,28.0,17122,6,0,...,14.0,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
27,4,431534,1,5,4,15,28.0,41787,7,0,...,5.0,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
28,4,431534,1,5,4,15,28.0,13176,8,1,...,10.3,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,10,New customer,5.813559,6.367797
29,5,3367565,1,6,2,7,19.0,196,1,1,...,9.0,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
30,5,3367565,1,6,2,7,19.0,12427,2,1,...,4.4,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
31,5,3367565,1,6,2,7,19.0,10258,3,1,...,3.0,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
32,5,3367565,1,6,2,7,19.0,25133,4,1,...,8.6,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797
33,6,550135,1,7,1,9,20.0,196,1,1,...,9.0,Mid-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
34,6,550135,1,7,1,9,20.0,10258,2,1,...,3.0,Low-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
35,6,550135,1,7,1,9,20.0,12427,3,1,...,4.4,Low-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
36,6,550135,1,7,1,9,20.0,25133,4,1,...,8.6,Mid-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
37,6,550135,1,7,1,9,20.0,13032,5,1,...,4.0,Low-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
38,7,3108588,1,8,1,14,14.0,12427,1,1,...,4.4,Low-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
39,7,3108588,1,8,1,14,14.0,196,2,1,...,9.0,Mid-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
40,7,3108588,1,8,1,14,14.0,10258,3,1,...,3.0,Low-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
41,7,3108588,1,8,1,14,14.0,25133,4,1,...,8.6,Mid-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
42,7,3108588,1,8,1,14,14.0,46149,5,0,...,13.4,Mid-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
43,7,3108588,1,8,1,14,14.0,49235,6,0,...,1.8,Low-range product,Busiest day,Busiest day,Busiests days,Average Orders,10,New customer,5.813559,6.367797
44,8,2295261,1,9,1,16,0.0,49235,1,1,...,1.8,Low-range product,Busiest day,Busiest day,Busiests days,Most Orders,10,New customer,5.813559,6.367797
45,8,2295261,1,9,1,16,0.0,46149,2,1,...,13.4,Mid-range product,Busiest day,Busiest day,Busiests days,Most Orders,10,New customer,5.813559,6.367797
46,8,2295261,1,9,1,16,0.0,25133,3,1,...,8.6,Mid-range product,Busiest day,Busiest day,Busiests days,Most Orders,10,New customer,5.813559,6.367797
47,8,2295261,1,9,1,16,0.0,196,4,1,...,9.0,Mid-range product,Busiest day,Busiest day,Busiests days,Most Orders,10,New customer,5.813559,6.367797
48,8,2295261,1,9,1,16,0.0,10258,5,1,...,3.0,Low-range product,Busiest day,Busiest day,Busiests days,Most Orders,10,New customer,5.813559,6.367797
49,8,2295261,1,9,1,16,0.0,12427,6,1,...,4.4,Low-range product,Busiest day,Busiest day,Busiests days,Most Orders,10,New customer,5.813559,6.367797
50,9,2550362,1,10,4,8,30.0,196,1,1,...,9.0,Mid-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
51,9,2550362,1,10,4,8,30.0,46149,2,1,...,13.4,Mid-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
52,9,2550362,1,10,4,8,30.0,39657,3,0,...,6.8,Mid-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
53,9,2550362,1,10,4,8,30.0,38928,4,0,...,12.6,Mid-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
54,9,2550362,1,10,4,8,30.0,25133,5,1,...,8.6,Mid-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
55,9,2550362,1,10,4,8,30.0,10258,6,1,...,3.0,Low-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
56,9,2550362,1,10,4,8,30.0,35951,7,0,...,1.3,Low-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
57,9,2550362,1,10,4,8,30.0,13032,8,1,...,4.0,Low-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
58,9,2550362,1,10,4,8,30.0,12427,9,1,...,4.4,Low-range product,Least busy,Least busy,Slowest days,Most Orders,10,New customer,5.813559,6.367797
59,11,2168274,2,1,2,11,NaN,32792,1,0,...,5.2,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
60,11,2168274,2,1,2,11,NaN,47766,2,0,...,6.3,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
61,11,2168274,2,1,2,11,NaN,20574,3,0,...,2.3,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
62,11,2168274,2,1,2,11,NaN,12000,4,0,...,10.9,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
63,11,2168274,2,1,2,11,NaN,48110,5,0,...,2.7,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
64,11,2168274,2,1,2,11,NaN,22474,6,0,...,4.1,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
65,11,2168274,2,1,2,11,NaN,16589,7,0,...,5.0,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
66,11,2168274,2,1,2,11,NaN,35917,8,0,...,9.4,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
67,11,2168274,2,1,2,11,NaN,27344,9,0,...,14.8,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
68,11,2168274,2,1,2,11,NaN,30489,10,0,...,7.5,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
69,11,2168274,2,1,2,11,NaN,27966,11,0,...,4.4,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
70,11,2168274,2,1,2,11,NaN,13176,12,0,...,10.3,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
71,11,2168274,2,1,2,11,NaN,45066,13,0,...,2.5,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
72,12,1501582,2,2,5,10,10.0,16797,1,0,...,1.3,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
73,12,1501582,2,2,5,10,10.0,47526,2,0,...,2.0,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
74,12,1501582,2,2,5,10,10.0,8479,3,0,...,3.5,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
75,12,1501582,2,2,5,10,10.0,47766,4,1,...,6.3,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
76,12,1501582,2,2,5,10,10.0,19051,5,0,...,3.9,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
77,12,1501582,2,2,5,10,10.0,8138,6,0,...,2.0,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
78,13,1901567,2,3,1,10,3.0,47766,1,1,...,6.3,Mid-range product,Busiest day,Busiest day,Busiests days,Fewest Orders,14,Regular customer,8.035897,7.515897
79,13,1901567,2,3,1,10,3.0,32792,2,1,...,5.2,Mid-range product,Busiest day,Busiest day,Busiests days,Fewest Orders,14,Regular customer,8.035897,7.515897
80,13,1901567,2,3,1,10,3.0,20574,3,1,...,2.3,Low-range product,Busiest day,Busiest day,Busiests days,Fewest Orders,14,Regular customer,8.035897,7.515897
81,13,1901567,2,3,1,10,3.0,7781,4,0,...,6.6,Mid-range product,Busiest day,Busiest day,Busiests days,Fewest Orders,14,Regular customer,8.035897,7.515897
82,13,1901567,2,3,1,10,3.0,28874,5,0,...,6.2,Mid-range product,Busiest day,Busiest day,Busiests days,Fewest Orders,14,Regular customer,8.035897,7.515897
83,14,738281,2,4,2,10,8.0,49451,1,0,...,7.1,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
84,14,738281,2,4,2,10,8.0,32792,2,1,...,5.2,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
85,14,738281,2,4,2,10,8.0,32139,3,0,...,7.5,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
86,14,738281,2,4,2,10,8.0,34688,4,0,...,5.8,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
87,14,738281,2,4,2,10,8.0,36735,5,0,...,8.9,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
88,14,738281,2,4,2,10,8.0,37646,6,0,...,9.1,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
89,14,738281,2,4,2,10,8.0,22829,7,0,...,5.5,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
90,14,738281,2,4,2,10,8.0,24852,8,0,...,12.3,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
91,14,738281,2,4,2,10,8.0,47209,9,0,...,4.0,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
92,14,738281,2,4,2,10,8.0,33276,10,0,...,10.8,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
93,14,738281,2,4,2,10,8.0,45613,11,0,...,12.6,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
94,14,738281,2,4,2,10,8.0,9681,12,0,...,2.0,Low-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
95,14,738281,2,4,2,10,8.0,21150,13,0,...,5.9,Mid-range product,Regularly busy,Regularly busy,Regularly busy,Fewest Orders,14,Regular customer,8.035897,7.515897
96,15,1673511,2,5,3,11,8.0,47144,1,0,...,14.0,Mid-range product,Least busy,Least busy,Slowest days,Fewest Orders,14,Regular customer,8.035897,7.515897
97,15,1673511,2,5,3,11,8.0,5322,2,0,...,2.9,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,14,Regular customer,8.035897,7.515897
98,15,1673511,2,5,3,11,8.0,17224,3,0,...,1.6,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,14,Regular customer,8.035897,7.515897
99,15,1673511,2,5,3,11,8.0,38656,4,0,...,3.4,Low-range product,Least busy,Least busy,Slowest days,Fewest Orders,14,Regular customer,8.035897,7.515897

In [32]:
## Deriving Columns with loc()
df_ords_prods.loc[df_ords_prods['mean_prices'] < 10, 'spending_flag'] = 'Low spender'

In [33]:
df_ords_prods.loc[df_ords_prods['mean_prices'] >= 10, 'spending_flag'] = 'High spender'

In [34]:
## printing
df_ords_prods['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     31934037
High spender       53144
Name: count, dtype: int64

In [36]:
df_ords_prods['spending_flag'].tail(100)

32434958    Low spender
32434959    Low spender
32434960    Low spender
32434961    Low spender
32434962    Low spender
32434963    Low spender
32434964    Low spender
32434965    Low spender
32434966    Low spender
32434967    Low spender
32434968    Low spender
32434969    Low spender
32434970    Low spender
32434971    Low spender
32434972    Low spender
32434973    Low spender
32434974    Low spender
32434976    Low spender
32434977    Low spender
32434978    Low spender
32434979    Low spender
32434980    Low spender
32434981    Low spender
32434982    Low spender
32434983    Low spender
32434984    Low spender
32434985    Low spender
32434986    Low spender
32434987    Low spender
32434988    Low spender
32434989    Low spender
32434990    Low spender
32434991    Low spender
32434992    Low spender
32434993    Low spender
32434994    Low spender
32434995    Low spender
32434996    Low spender
32434997    Low spender
32434998    Low spender
32434999    Low spender
32435000    Low spender
32435001    Low spender
32435002    Low spender
32435003    Low spender
32435004    Low spender
32435005    Low spender
32435006    Low spender
32435007    Low spender
32435008    Low spender
32435009    Low spender
32435010    Low spender
32435011    Low spender
32435012    Low spender
32435013    Low spender
32435014    Low spender
32435015    Low spender
32435016    Low spender
32435017    Low spender
32435018    Low spender
32435019    Low spender
32435020    Low spender
32435021    Low spender
32435022    Low spender
32435023    Low spender
32435024    Low spender
32435025    Low spender
32435026    Low spender
32435027    Low spender
32435028    Low spender
32435029    Low spender
32435030    Low spender
32435031    Low spender
32435032    Low spender
32435033    Low spender
32435034    Low spender
32435035    Low spender
32435036    Low spender
32435037    Low spender
32435038    Low spender
32435039    Low spender
32435040    Low spender
32435041    Low spender
32435042    Low spender
32435043    Low spender
32435044    Low spender
32435045    Low spender
32435046    Low spender
32435047    Low spender
32435048    Low spender
32435049    Low spender
32435050    Low spender
32435051    Low spender
32435052    Low spender
32435053    Low spender
32435054    Low spender
32435055    Low spender
32435056    Low spender
32435057    Low spender
32435058    Low spender
Name: spending_flag, dtype: object

In [37]:
df_ords_prods[['user_id', 'spending_flag', 'mean_prices']].head(60)

    user_id spending_flag  mean_prices
0         1   Low spender     6.367797
1         1   Low spender     6.367797
2         1   Low spender     6.367797
3         1   Low spender     6.367797
4         1   Low spender     6.367797
5         1   Low spender     6.367797
6         1   Low spender     6.367797
7         1   Low spender     6.367797
8         1   Low spender     6.367797
9         1   Low spender     6.367797
10        1   Low spender     6.367797
11        1   Low spender     6.367797
12        1   Low spender     6.367797
13        1   Low spender     6.367797
14        1   Low spender     6.367797
15        1   Low spender     6.367797
16        1   Low spender     6.367797
17        1   Low spender     6.367797
18        1   Low spender     6.367797
19        1   Low spender     6.367797
20        1   Low spender     6.367797
21        1   Low spender     6.367797
22        1   Low spender     6.367797
23        1   Low spender     6.367797
24        1   Low spender     6.367797
25        1   Low spender     6.367797
26        1   Low spender     6.367797
27        1   Low spender     6.367797
28        1   Low spender     6.367797
29        1   Low spender     6.367797
30        1   Low spender     6.367797
31        1   Low spender     6.367797
32        1   Low spender     6.367797
33        1   Low spender     6.367797
34        1   Low spender     6.367797
35        1   Low spender     6.367797
36        1   Low spender     6.367797
37        1   Low spender     6.367797
38        1   Low spender     6.367797
39        1   Low spender     6.367797
40        1   Low spender     6.367797
41        1   Low spender     6.367797
42        1   Low spender     6.367797
43        1   Low spender     6.367797
44        1   Low spender     6.367797
45        1   Low spender     6.367797
46        1   Low spender     6.367797
47        1   Low spender     6.367797
48        1   Low spender     6.367797
49        1   Low spender     6.367797
50        1   Low spender     6.367797
51        1   Low spender     6.367797
52        1   Low spender     6.367797
53        1   Low spender     6.367797
54        1   Low spender     6.367797
55        1   Low spender     6.367797
56        1   Low spender     6.367797
57        1   Low spender     6.367797
58        1   Low spender     6.367797
59        2   Low spender     7.515897

In [38]:
## Step7.
# Calculate median days_since_prior_order per user
df_ords_prods['median_days_since_prior_order'] = df_ords_prods.groupby('user_id')['days_since_prior_order'].transform('median')

/var/folders/n5/lt6zjw5j12s3tv1t42m14nqh0000gn/T/ipykernel_14229/4183671591.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ords_prods['median_days_since_prior_order'] = df_ords_prods.groupby('user_id')['days_since_prior_order'].transform('median')

In [44]:
# Make sure df_ords_prods is a copy
df_ords_prods = df_ords_prods.copy()

In [45]:
## Step7.
# Calculate median days_since_prior_order per user
df_ords_prods['median_days_since_prior_order'] = df_ords_prods.groupby('user_id')['days_since_prior_order'].transform('median')

In [46]:
# Deriving columns with loc()
df_ords_prods.loc[df_ords_prods['median_days_since_prior_order'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [47]:
df_ords_prods.loc[
    (df_ords_prods['median_days_since_prior_order'] > 10) & (df_ords_prods['median_days_since_prior_order'] <= 20), 
    'order_frequency_flag'] = 'Regular customer'

In [52]:
df_ords_prods.loc[df_ords_prods['median_days_since_prior_order'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [53]:
df_ords_prods.head()

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,busiest_days,busiests_days,busiest_period_of_day,max_order,loyalty_flag,mean_price_order,mean_prices,spending_flag,median_days_since_prior_order,order_frequency_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797,Low spender,20.5,Non-frequent customer
1,0,2539329,1,1,2,8,NaN,14084,2,0,...,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797,Low spender,20.5,Non-frequent customer
2,0,2539329,1,1,2,8,NaN,12427,3,0,...,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797,Low spender,20.5,Non-frequent customer
3,0,2539329,1,1,2,8,NaN,26088,4,0,...,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797,Low spender,20.5,Non-frequent customer
4,0,2539329,1,1,2,8,NaN,26405,5,0,...,Regularly busy,Regularly busy,Fewest Orders,10,New customer,5.813559,6.367797,Low spender,20.5,Non-frequent customer

In [56]:
df_ords_prods[['user_id', 'order_frequency_flag', 'median_days_since_prior_order']].head(60)

    user_id   order_frequency_flag  median_days_since_prior_order
0         1  Non-frequent customer                           20.5
1         1  Non-frequent customer                           20.5
2         1  Non-frequent customer                           20.5
3         1  Non-frequent customer                           20.5
4         1  Non-frequent customer                           20.5
5         1  Non-frequent customer                           20.5
6         1  Non-frequent customer                           20.5
7         1  Non-frequent customer                           20.5
8         1  Non-frequent customer                           20.5
9         1  Non-frequent customer                           20.5
10        1  Non-frequent customer                           20.5
11        1  Non-frequent customer                           20.5
12        1  Non-frequent customer                           20.5
13        1  Non-frequent customer                           20.5
14        1  Non-frequent customer                           20.5
15        1  Non-frequent customer                           20.5
16        1  Non-frequent customer                           20.5
17        1  Non-frequent customer                           20.5
18        1  Non-frequent customer                           20.5
19        1  Non-frequent customer                           20.5
20        1  Non-frequent customer                           20.5
21        1  Non-frequent customer                           20.5
22        1  Non-frequent customer                           20.5
23        1  Non-frequent customer                           20.5
24        1  Non-frequent customer                           20.5
25        1  Non-frequent customer                           20.5
26        1  Non-frequent customer                           20.5
27        1  Non-frequent customer                           20.5
28        1  Non-frequent customer                           20.5
29        1  Non-frequent customer                           20.5
30        1  Non-frequent customer                           20.5
31        1  Non-frequent customer                           20.5
32        1  Non-frequent customer                           20.5
33        1  Non-frequent customer                           20.5
34        1  Non-frequent customer                           20.5
35        1  Non-frequent customer                           20.5
36        1  Non-frequent customer                           20.5
37        1  Non-frequent customer                           20.5
38        1  Non-frequent customer                           20.5
39        1  Non-frequent customer                           20.5
40        1  Non-frequent customer                           20.5
41        1  Non-frequent customer                           20.5
42        1  Non-frequent customer                           20.5
43        1  Non-frequent customer                           20.5
44        1  Non-frequent customer                           20.5
45        1  Non-frequent customer                           20.5
46        1  Non-frequent customer                           20.5
47        1  Non-frequent customer                           20.5
48        1  Non-frequent customer                           20.5
49        1  Non-frequent customer                           20.5
50        1  Non-frequent customer                           20.5
51        1  Non-frequent customer                           20.5
52        1  Non-frequent customer                           20.5
53        1  Non-frequent customer                           20.5
54        1  Non-frequent customer                           20.5
55        1  Non-frequent customer                           20.5
56        1  Non-frequent customer                           20.5
57        1  Non-frequent customer                           20.5
58        1  Non-frequent customer                           20.5
59        2       Regular customer                           13.0

In [57]:
## Exporting DataFrame
df_ords_prods.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_new_variables3.pkl'))

In [58]:
## Exporting DataFrame
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_new_variables4.pkl'))